const DEFAULT_SHARDS = 50
const DEFAULT_HEALTH = 0
const DEFAULT_PLACEMENT_TTL = 1000 * 30
const DEFAULT_ASSIGNMENT_TTL = 1000 * 30
const DEFAULT_WAR_TTL = 1000 * 30
const DEFAULT_MAX_ROUNDS = 100000
const DEFAULT_SHARDS_PER_ROUND = 10
const ROOM_ID = `2ruk2zo3x8k11h5`
const DEFAULT_CHAT_TTL = 1000 * 60 * 10
const DEFAULT_MAX_CHATS = 20
const DEFAULT_CHAT_MAX_MESSAGE_LENGTH = 200
const DEFAULT_CELL_SELF_DESTRUCT_TTL = 1000 * 60 * 5 // 5 minutes

module.exports = {
  DEFAULT_MAX_ROUNDS,
  DEFAULT_SHARDS,
  DEFAULT_HEALTH,
  DEFAULT_PLACEMENT_TTL,
  DEFAULT_ASSIGNMENT_TTL,
  DEFAULT_WAR_TTL,
  DEFAULT_SHARDS_PER_ROUND,
  ROOM_ID,
  DEFAULT_CHAT_TTL,
  DEFAULT_MAX_CHATS,
  DEFAULT_CHAT_MAX_MESSAGE_LENGTH,
  DEFAULT_CELL_SELF_DESTRUCT_TTL,
}
