const DEFAULT_SHARDS = 50
const DEFAULT_HEALTH = 0
const DEFAULT_PLACEMENT_TTL = 1000 * 30
const DEFAULT_ASSIGNMENT_TTL = 1000 * 30
const DEFAULT_WAR_TTL = 1000 * 30
const ROOM_ID = `2ruk2zo3x8k11h5`

module.exports = {
  DEFAULT_SHARDS,
  DEFAULT_HEALTH,
  DEFAULT_PLACEMENT_TTL,
  DEFAULT_ASSIGNMENT_TTL,
  DEFAULT_WAR_TTL,
  ROOM_ID,
}
